version: '3.8'

volumes:
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/hwiemann/data/wordpress
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/hwiemann/data/mariadb

networks:
  inception_network:
    driver: bridge

services:
  mariadb:
    build: ./mariadb
    container_name: mariadb
    env_file:
      - .env
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - inception_network
    restart: unless-stopped

  wordpress:
    build: ./wordpress
    container_name: wordpress
    env_file:
      - .env
    volumes:
      - wordpress_data:/var/www/html
    user: "www-data:www-data"
    depends_on:
      - mariadb
    networks:
      - inception_network
    restart: unless-stopped


  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - "443:443"
    env_file:
      - .env
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/ssl:/etc/nginx/ssl
      - wordpress_data:/var/www/html
    depends_on:
      - wordpress
    networks:
      - inception_network
    restart: unless-stopped



